"""add access token table for password reset

Revision ID: 20b39fbcf257
Revises: 43b2edcd6393
Create Date: 2026-03-18 12:57:36.458148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b39fbcf257'
down_revision: Union[str, Sequence[str], None] = '43b2edcd6393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reset_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reset_tokens'))
    )
    op.create_index(op.f('ix_reset_tokens_token_hash'), 'reset_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_tokens_token_hash'), table_name='reset_tokens')
    op.drop_table('reset_tokens')
    # ### end Alembic commands ###
