"""add account_type to account model

Revision ID: 43b2edcd6393
Revises: b61bfbb56224
Create Date: 2026-03-18 02:06:46.112942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b2edcd6393'
down_revision: Union[str, Sequence[str], None] = 'b61bfbb56224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_type', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_type')
    # ### end Alembic commands ###
