"""harden transaction model for deduping

Revision ID: 6aa186501e6e
Revises: cb14ef0ffe78
Create Date: 2026-03-22 00:11:20.284101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa186501e6e'
down_revision: Union[str, Sequence[str], None] = 'cb14ef0ffe78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('normalized_description', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('import_source', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('import_batch_id', sa.Uuid(), nullable=True))
    op.add_column('transactions', sa.Column('external_tx_id', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('dedupe_fingerprint', sa.String(length=64), nullable=False))
    op.add_column('transactions', sa.Column('is_auto_categorized', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('auto_category_confidence', sa.Float(), nullable=True))
    op.alter_column('transactions', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_transactions_dedupe_fingerprint'), 'transactions', ['dedupe_fingerprint'], unique=False)
    op.create_index(op.f('ix_transactions_external_tx_id'), 'transactions', ['external_tx_id'], unique=False)
    op.create_index(op.f('ix_transactions_import_batch_id'), 'transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_normalized_description'), 'transactions', ['normalized_description'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_unique_constraint('uq_transaction_user_account_fingerprint', 'transactions', ['user_id', 'account_id', 'dedupe_fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_user_account_fingerprint', 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_normalized_description'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_import_batch_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_tx_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_dedupe_fingerprint'), table_name='transactions')
    op.alter_column('transactions', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('transactions', 'auto_category_confidence')
    op.drop_column('transactions', 'is_auto_categorized')
    op.drop_column('transactions', 'dedupe_fingerprint')
    op.drop_column('transactions', 'external_tx_id')
    op.drop_column('transactions', 'import_batch_id')
    op.drop_column('transactions', 'import_source')
    op.drop_column('transactions', 'normalized_description')
    # ### end Alembic commands ###
